//! Read TUNEX_GATEWAY_URL from .env at compile time and generate GATEWAY_URL constant.

use std::env;
use std::fs;
use std::path::Path;

const DEFAULT_GATEWAY_URL: &str = "http://127.0.0.1:8080";
const ENV_VAR: &str = "TUNEX_GATEWAY_URL";

fn main() {
    let gateway_url = read_gateway_url();
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let path = Path::new(&out_dir).join("gateway_url.rs");
    let content = format!(
        r#"// Generated by build.rs — do not edit.
pub const GATEWAY_URL: &str = "{}";
"#,
        gateway_url.replace('\\', "\\\\").replace('"', "\\\"")
    );
    fs::write(&path, content).expect("write gateway_url.rs");
    println!("cargo:rerun-if-env-changed={}", ENV_VAR);
    println!("cargo:rerun-if-changed=.env");
}

fn read_gateway_url() -> String {
    if let Ok(url) = env::var(ENV_VAR) {
        let url = url.trim();
        if !url.is_empty() {
            return url.to_string();
        }
    }

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let mut candidates = vec![Path::new(&manifest_dir).join(".env")];
    if let Some(parent) = Path::new(&manifest_dir).parent() {
        candidates.push(parent.join(".env"));
    }

    for path in &candidates {
        if path.exists() {
            if let Ok(content) = fs::read_to_string(path) {
                for line in content.lines() {
                    let line = line.trim();
                    if line.starts_with('#') || line.is_empty() {
                        continue;
                    }
                    if let Some(rest) = line.strip_prefix(ENV_VAR) {
                        let rest = rest.trim();
                        if rest.starts_with('=') {
                            let value = rest[1..].trim().trim_matches('"').trim_matches('\'');
                            if !value.is_empty() {
                                return value.to_string();
                            }
                        }
                        break;
                    }
                }
            }
        }
    }

    DEFAULT_GATEWAY_URL.to_string()
}
