[package]
name = "tunex-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["ws", "json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync"] }
tunex-common = { path = "../crates/tunex-common" }
serde_json = "1.0"
tower = "0.4"
http = "1.0"
futures-util = "0.3"
sea-orm = { version = "1.0", features = ["runtime-tokio", "sqlx-postgres", "macros"] }
sea-orm-migration = "1.0"
async-trait = "0.1"
